stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.8.7-slim-buster
  before_script:
    - mkdir /tmp/nextflow && cd /tmp/nextflow && (wget https://get.nextflow.io | bash) && chmod 755 nextflow $$ export PATH=/tmp/:$PATH && cd -
    - nextflow -version
    - python -m pip install --upgrade pip
    - pip install pytest certifi twine
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - python setup.py install
    # reduce the default SSL security level to get around a misconfiguration in the Ensembl server
    # https://github.com/Ensembl/ensembl-rest/issues/427
    # See https://askubuntu.com/a/1233456
    - sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/' /usr/lib/ssl/openssl.cnf
  script:
    - PYTHONPATH=. pytest tests
  environment:
    name: test-env
  only:
    - external_pull_requests
    - tags
    - master


deploy-python-package-production:
  stage: deploy
  image: python:3.8.7-slim-buster
  script:
    - python setup.py sdist
    - twine upload dist/*
  dependencies:
    - test
  variables:
    TWINE_NON_INTERACTIVE: "true"
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  only:
    - tags

